// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: protos/detect_object.proto

package main

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DetectObject_Request_FullMethodName = "/DetectObject/Request"
)

// DetectObjectClient is the client API for DetectObject service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DetectObjectClient interface {
	Request(ctx context.Context, in *RequestPayload, opts ...grpc.CallOption) (*ResponsePayload, error)
}

type detectObjectClient struct {
	cc grpc.ClientConnInterface
}

func NewDetectObjectClient(cc grpc.ClientConnInterface) DetectObjectClient {
	return &detectObjectClient{cc}
}

func (c *detectObjectClient) Request(ctx context.Context, in *RequestPayload, opts ...grpc.CallOption) (*ResponsePayload, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponsePayload)
	err := c.cc.Invoke(ctx, DetectObject_Request_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DetectObjectServer is the server API for DetectObject service.
// All implementations must embed UnimplementedDetectObjectServer
// for forward compatibility.
type DetectObjectServer interface {
	Request(context.Context, *RequestPayload) (*ResponsePayload, error)
	mustEmbedUnimplementedDetectObjectServer()
}

// UnimplementedDetectObjectServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDetectObjectServer struct{}

func (UnimplementedDetectObjectServer) Request(context.Context, *RequestPayload) (*ResponsePayload, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Request not implemented")
}
func (UnimplementedDetectObjectServer) mustEmbedUnimplementedDetectObjectServer() {}
func (UnimplementedDetectObjectServer) testEmbeddedByValue()                      {}

// UnsafeDetectObjectServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DetectObjectServer will
// result in compilation errors.
type UnsafeDetectObjectServer interface {
	mustEmbedUnimplementedDetectObjectServer()
}

func RegisterDetectObjectServer(s grpc.ServiceRegistrar, srv DetectObjectServer) {
	// If the following call pancis, it indicates UnimplementedDetectObjectServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DetectObject_ServiceDesc, srv)
}

func _DetectObject_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectObjectServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DetectObject_Request_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectObjectServer).Request(ctx, req.(*RequestPayload))
	}
	return interceptor(ctx, in, info, handler)
}

// DetectObject_ServiceDesc is the grpc.ServiceDesc for DetectObject service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DetectObject_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "DetectObject",
	HandlerType: (*DetectObjectServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Request",
			Handler:    _DetectObject_Request_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/detect_object.proto",
}
