// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: protos/detect_object.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BoxXYWH struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	W             float32                `protobuf:"fixed32,3,opt,name=w,proto3" json:"w,omitempty"`
	H             float32                `protobuf:"fixed32,4,opt,name=h,proto3" json:"h,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoxXYWH) Reset() {
	*x = BoxXYWH{}
	mi := &file_protos_detect_object_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoxXYWH) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoxXYWH) ProtoMessage() {}

func (x *BoxXYWH) ProtoReflect() protoreflect.Message {
	mi := &file_protos_detect_object_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoxXYWH.ProtoReflect.Descriptor instead.
func (*BoxXYWH) Descriptor() ([]byte, []int) {
	return file_protos_detect_object_proto_rawDescGZIP(), []int{0}
}

func (x *BoxXYWH) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BoxXYWH) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *BoxXYWH) GetW() float32 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *BoxXYWH) GetH() float32 {
	if x != nil {
		return x.H
	}
	return 0
}

type Detection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Box           *BoxXYWH               `protobuf:"bytes,1,opt,name=box,proto3" json:"box,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	ClassId       int32                  `protobuf:"varint,3,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	ClassName     string                 `protobuf:"bytes,4,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"` // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detection) Reset() {
	*x = Detection{}
	mi := &file_protos_detect_object_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detection) ProtoMessage() {}

func (x *Detection) ProtoReflect() protoreflect.Message {
	mi := &file_protos_detect_object_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detection.ProtoReflect.Descriptor instead.
func (*Detection) Descriptor() ([]byte, []int) {
	return file_protos_detect_object_proto_rawDescGZIP(), []int{1}
}

func (x *Detection) GetBox() *BoxXYWH {
	if x != nil {
		return x.Box
	}
	return nil
}

func (x *Detection) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Detection) GetClassId() int32 {
	if x != nil {
		return x.ClassId
	}
	return 0
}

func (x *Detection) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

type ResponsePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Objects       []*Detection           `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponsePayload) Reset() {
	*x = ResponsePayload{}
	mi := &file_protos_detect_object_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponsePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponsePayload) ProtoMessage() {}

func (x *ResponsePayload) ProtoReflect() protoreflect.Message {
	mi := &file_protos_detect_object_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponsePayload.ProtoReflect.Descriptor instead.
func (*ResponsePayload) Descriptor() ([]byte, []int) {
	return file_protos_detect_object_proto_rawDescGZIP(), []int{2}
}

func (x *ResponsePayload) GetObjects() []*Detection {
	if x != nil {
		return x.Objects
	}
	return nil
}

type RequestPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specifies the data source for inference. sending the image as rgba byte array.
	ImageRgbaBytes []byte `protobuf:"bytes,1,opt,name=image_rgba_bytes,json=imageRgbaBytes,proto3" json:"image_rgba_bytes,omitempty"`
	ImageWidth     int32  `protobuf:"varint,2,opt,name=image_width,json=imageWidth,proto3" json:"image_width,omitempty"`
	ImageHeight    int32  `protobuf:"varint,3,opt,name=image_height,json=imageHeight,proto3" json:"image_height,omitempty"`
	//	Sets the minimum confidence threshold for detections.
	//
	// Objects detected with confidence below this threshold will be disregarded.
	// Adjusting this value can help reduce false positives.
	ConfidenceThreshold float32 `protobuf:"fixed32,4,opt,name=confidence_threshold,json=confidenceThreshold,proto3" json:"confidence_threshold,omitempty"`
	// Intersection Over Union (IoU) threshold for Non-Maximum Suppression (NMS).
	// Lower values result in fewer detections by eliminating overlapping boxes, useful for reducing duplicates.
	IouThreshold  float32 `protobuf:"fixed32,5,opt,name=iou_threshold,json=iouThreshold,proto3" json:"iou_threshold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPayload) Reset() {
	*x = RequestPayload{}
	mi := &file_protos_detect_object_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPayload) ProtoMessage() {}

func (x *RequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_protos_detect_object_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPayload.ProtoReflect.Descriptor instead.
func (*RequestPayload) Descriptor() ([]byte, []int) {
	return file_protos_detect_object_proto_rawDescGZIP(), []int{3}
}

func (x *RequestPayload) GetImageRgbaBytes() []byte {
	if x != nil {
		return x.ImageRgbaBytes
	}
	return nil
}

func (x *RequestPayload) GetImageWidth() int32 {
	if x != nil {
		return x.ImageWidth
	}
	return 0
}

func (x *RequestPayload) GetImageHeight() int32 {
	if x != nil {
		return x.ImageHeight
	}
	return 0
}

func (x *RequestPayload) GetConfidenceThreshold() float32 {
	if x != nil {
		return x.ConfidenceThreshold
	}
	return 0
}

func (x *RequestPayload) GetIouThreshold() float32 {
	if x != nil {
		return x.IouThreshold
	}
	return 0
}

var File_protos_detect_object_proto protoreflect.FileDescriptor

const file_protos_detect_object_proto_rawDesc = "" +
	"\n" +
	"\x1aprotos/detect_object.proto\"A\n" +
	"\aBoxXYWH\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01w\x18\x03 \x01(\x02R\x01w\x12\f\n" +
	"\x01h\x18\x04 \x01(\x02R\x01h\"w\n" +
	"\tDetection\x12\x1a\n" +
	"\x03box\x18\x01 \x01(\v2\b.BoxXYWHR\x03box\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12\x19\n" +
	"\bclass_id\x18\x03 \x01(\x05R\aclassId\x12\x1d\n" +
	"\n" +
	"class_name\x18\x04 \x01(\tR\tclassName\"7\n" +
	"\x0fResponsePayload\x12$\n" +
	"\aobjects\x18\x01 \x03(\v2\n" +
	".DetectionR\aobjects\"\xd6\x01\n" +
	"\x0eRequestPayload\x12(\n" +
	"\x10image_rgba_bytes\x18\x01 \x01(\fR\x0eimageRgbaBytes\x12\x1f\n" +
	"\vimage_width\x18\x02 \x01(\x05R\n" +
	"imageWidth\x12!\n" +
	"\fimage_height\x18\x03 \x01(\x05R\vimageHeight\x121\n" +
	"\x14confidence_threshold\x18\x04 \x01(\x02R\x13confidenceThreshold\x12#\n" +
	"\riou_threshold\x18\x05 \x01(\x02R\fiouThreshold2>\n" +
	"\fDetectObject\x12.\n" +
	"\aRequest\x12\x0f.RequestPayload\x1a\x10.ResponsePayload\"\x00B\x16Z\x14github.com/main/mainb\x06proto3"

var (
	file_protos_detect_object_proto_rawDescOnce sync.Once
	file_protos_detect_object_proto_rawDescData []byte
)

func file_protos_detect_object_proto_rawDescGZIP() []byte {
	file_protos_detect_object_proto_rawDescOnce.Do(func() {
		file_protos_detect_object_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_detect_object_proto_rawDesc), len(file_protos_detect_object_proto_rawDesc)))
	})
	return file_protos_detect_object_proto_rawDescData
}

var file_protos_detect_object_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_detect_object_proto_goTypes = []any{
	(*BoxXYWH)(nil),         // 0: BoxXYWH
	(*Detection)(nil),       // 1: Detection
	(*ResponsePayload)(nil), // 2: ResponsePayload
	(*RequestPayload)(nil),  // 3: RequestPayload
}
var file_protos_detect_object_proto_depIdxs = []int32{
	0, // 0: Detection.box:type_name -> BoxXYWH
	1, // 1: ResponsePayload.objects:type_name -> Detection
	3, // 2: DetectObject.Request:input_type -> RequestPayload
	2, // 3: DetectObject.Request:output_type -> ResponsePayload
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_detect_object_proto_init() }
func file_protos_detect_object_proto_init() {
	if File_protos_detect_object_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_detect_object_proto_rawDesc), len(file_protos_detect_object_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_detect_object_proto_goTypes,
		DependencyIndexes: file_protos_detect_object_proto_depIdxs,
		MessageInfos:      file_protos_detect_object_proto_msgTypes,
	}.Build()
	File_protos_detect_object_proto = out.File
	file_protos_detect_object_proto_goTypes = nil
	file_protos_detect_object_proto_depIdxs = nil
}
